"""
Amministrazione schemas package
"""
from .fornitore import FornitoreCreate, FornitoreUpdate, FornitoreResponse
from .fornitore_tipo import FornitoreTipoCreate, FornitoreTipoUpdate, FornitoreTipoResponse
from .vendita_prodotto_agricolo import VenditaProdottoAgricoloCreate, VenditaProdottoAgricoloUpdate, VenditaProdottoAgricoloResponse
from .prodotto_derivato import ProdottoDerivatoCreate, ProdottoDerivatoUpdate, ProdottoDerivatoResponse
from .fattura_amministrazione import (
    FatturaAmministrazioneCreate,
    FatturaAmministrazioneUpdate,
    FatturaAmministrazioneResponse,
    FatturaAmministrazioneLineaResponse,
    FatturaAmministrazioneRiepilogoResponse,
    FatturaAmministrazionePagamentoResponse,
    FatturaAmministrazioneRicezioneResponse,
)
from .fattura_emessa import FatturaEmessaCreate, FatturaEmessaUpdate, FatturaEmessaResponse, FatturaEmessaWithPagamenti, FatturaEmessaSummary
from .pagamento import PagamentoCreate, PagamentoUpdate, PagamentoResponse
from .prima_nota import PrimaNotaCreate, PrimaNotaUpdate, PrimaNotaResponse, PrimaNotaSummary
from .pn import (
    PNCategoriaBase,
    PNCategoriaCreate,
    PNCategoriaUpdate,
    PNCategoriaResponse,
    PNContoCreate,
    PNContoIbanCreate,
    PNContoIbanResponse,
    PNContoIbanUpdate,
    PNContoResponse,
    PNContoUpdate,
    PNDocumentoApertoResponse,
    PNMovimentiListResponse,
    PNMovimentoCreate,
    PNMovimentoDocumentoInput,
    PNMovimentoDocumentoResponse,
    PNMovimentoResponse,
    PNMovimentoUpdate,
    PNPreferenzeResponse,
    PNRiepilogoResponse,
    PNSetupResponse,
    SoccidaAccontoCreate,
    SoccidaAccontoResponse,
    SyncFattureResponse,
    SyncFattureErrorItem,
)
from .attrezzatura import (
    AttrezzaturaCreate,
    AttrezzaturaUpdate,
    AttrezzaturaResponse,
    AttrezzaturaWithDetails,
    ScadenzaAttrezzaturaCreate,
    ScadenzaAttrezzaturaUpdate,
    ScadenzaAttrezzaturaResponse,
    AmmortamentoCreate,
    AmmortamentoUpdate,
    AmmortamentoResponse,
    AttrezzaturaCostWindow,
    AttrezzaturaCostiRiepilogo,
)
from .assicurazione_aziendale import AssicurazioneAziendaleCreate, AssicurazioneAziendaleUpdate, AssicurazioneAziendaleResponse, AssicurazioneAziendaleSummary
from .partita_animale import PartitaAnimaleCreate, PartitaAnimaleUpdate, PartitaAnimaleResponse, PartitaAnimaleConfirm
from .contratto_soccida import (
    ContrattoSoccidaCreate,
    ContrattoSoccidaUpdate,
    ContrattoSoccidaResponse,
    ContrattoSoccidaWithRelations,
)
from .partita_animale import (
    PartitaMovimentoFinanziarioCreate,
    PartitaMovimentoFinanziarioUpdate,
    PartitaMovimentoFinanziarioResponse,
)
from .ddt_emesso import (
    DdtEmessoCreate,
    DdtEmessoUpdate,
    DdtEmessoResponse,
    ArticoloDDT,
)

__all__ = [
    "FornitoreCreate",
    "FornitoreUpdate",
    "FornitoreResponse",
    "FornitoreTipoCreate",
    "FornitoreTipoUpdate",
    "FornitoreTipoResponse",
    "VenditaProdottoAgricoloCreate",
    "VenditaProdottoAgricoloUpdate",
    "VenditaProdottoAgricoloResponse",
    "ProdottoDerivatoCreate",
    "ProdottoDerivatoUpdate",
    "ProdottoDerivatoResponse",
    "FatturaAmministrazioneCreate",
    "FatturaAmministrazioneUpdate",
    "FatturaAmministrazioneResponse",
    "FatturaAmministrazioneLineaResponse",
    "FatturaAmministrazioneRiepilogoResponse",
    "FatturaAmministrazionePagamentoResponse",
    "FatturaAmministrazioneRicezioneResponse",
    "FatturaEmessaCreate",
    "FatturaEmessaUpdate",
    "FatturaEmessaResponse",
    "FatturaEmessaWithPagamenti",
    "FatturaEmessaSummary",
    "PagamentoCreate",
    "PagamentoUpdate",
    "PagamentoResponse",
    "PrimaNotaCreate",
    "PrimaNotaUpdate",
    "PrimaNotaResponse",
    "PrimaNotaSummary",
    "PNSetupResponse",
    "PNMovimentiListResponse",
    "PNMovimentoCreate",
    "PNMovimentoUpdate",
    "PNMovimentoResponse",
    "PNContoCreate",
    "PNContoResponse",
    "PNContoUpdate",
    "PNContoIbanCreate",
    "PNContoIbanUpdate",
    "PNContoIbanResponse",
    "PNCategoriaBase",
    "PNCategoriaCreate",
    "PNCategoriaUpdate",
    "PNCategoriaResponse",
    "PNPreferenzeResponse",
    "PNDocumentoApertoResponse",
    "AttrezzaturaCreate",
    "AttrezzaturaUpdate",
    "AttrezzaturaResponse",
    "AttrezzaturaWithDetails",
    "ScadenzaAttrezzaturaCreate",
    "ScadenzaAttrezzaturaUpdate",
    "ScadenzaAttrezzaturaResponse",
    "AmmortamentoCreate",
    "AmmortamentoUpdate",
    "AmmortamentoResponse",
    "AttrezzaturaCostWindow",
    "AttrezzaturaCostiRiepilogo",
    "AssicurazioneAziendaleCreate",
    "AssicurazioneAziendaleUpdate",
    "AssicurazioneAziendaleResponse",
    "AssicurazioneAziendaleSummary",
    "PartitaAnimaleCreate",
    "PartitaAnimaleUpdate",
    "PartitaAnimaleResponse",
    "PartitaAnimaleConfirm",
    "PartitaMovimentoFinanziarioCreate",
    "PartitaMovimentoFinanziarioUpdate",
    "PartitaMovimentoFinanziarioResponse",
    "ContrattoSoccidaCreate",
    "ContrattoSoccidaUpdate",
    "ContrattoSoccidaResponse",
    "ContrattoSoccidaWithRelations",
    "SoccidaAccontoCreate",
    "SoccidaAccontoResponse",
    "SyncFattureResponse",
    "SyncFattureErrorItem",
    "DdtEmessoCreate",
    "DdtEmessoUpdate",
    "DdtEmessoResponse",
    "ArticoloDDT",
]

