"""add_sanitario_module_tables

Revision ID: 01ce1ccd56e3
Revises: 89df08758288
Create Date: 2025-10-29 21:09:00.392874

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '01ce1ccd56e3'
down_revision = '89df08758288'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('farmaci',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome_commerciale', sa.String(length=200), nullable=False),
    sa.Column('principio_attivo', sa.String(length=200), nullable=True),
    sa.Column('unita_misura', sa.String(length=20), nullable=True),
    sa.Column('descrizione', sa.Text(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_farmaci_deleted_at'), 'farmaci', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_farmaci_id'), 'farmaci', ['id'], unique=False)
    op.create_index(op.f('ix_farmaci_nome_commerciale'), 'farmaci', ['nome_commerciale'], unique=False)
    op.create_table('lotti_farmaco',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('azienda_id', sa.Integer(), nullable=False),
    sa.Column('farmaco_id', sa.Integer(), nullable=False),
    sa.Column('lotto', sa.String(length=50), nullable=False),
    sa.Column('scadenza', sa.Date(), nullable=True),
    sa.Column('quantita_iniziale', sa.Numeric(precision=10, scale=2), server_default='0', nullable=False),
    sa.Column('quantita_rimanente', sa.Numeric(precision=10, scale=2), server_default='0', nullable=False),
    sa.Column('fornitore', sa.String(length=200), nullable=True),
    sa.Column('numero_fattura', sa.String(length=100), nullable=True),
    sa.Column('data_acquisto', sa.Date(), nullable=True),
    sa.Column('note', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('quantita_iniziale >= 0', name='check_quantita_iniziale_positiva'),
    sa.CheckConstraint('quantita_rimanente <= quantita_iniziale', name='check_quantita_rimanente_logic'),
    sa.CheckConstraint('quantita_rimanente >= 0', name='check_quantita_rimanente_positiva'),
    sa.ForeignKeyConstraint(['azienda_id'], ['aziende.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['farmaco_id'], ['farmaci.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lotti_farmaco_azienda_id'), 'lotti_farmaco', ['azienda_id'], unique=False)
    op.create_index(op.f('ix_lotti_farmaco_deleted_at'), 'lotti_farmaco', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_lotti_farmaco_farmaco_id'), 'lotti_farmaco', ['farmaco_id'], unique=False)
    op.create_index(op.f('ix_lotti_farmaco_id'), 'lotti_farmaco', ['id'], unique=False)
    op.create_index(op.f('ix_lotti_farmaco_scadenza'), 'lotti_farmaco', ['scadenza'], unique=False)
    op.create_table('somministrazioni',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('animale_id', sa.Integer(), nullable=False),
    sa.Column('farmaco_id', sa.Integer(), nullable=False),
    sa.Column('lotto_farmaco_id', sa.Integer(), nullable=True),
    sa.Column('data_ora', sa.DateTime(timezone=True), nullable=False),
    sa.Column('quantita', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('operatore_id', sa.Integer(), nullable=True),
    sa.Column('operatore_nome', sa.String(length=100), nullable=True),
    sa.Column('veterinario', sa.String(length=100), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('reazioni_avverse', sa.Text(), nullable=True),
    sa.Column('periodo_sospensione', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['animale_id'], ['animali.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['farmaco_id'], ['farmaci.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['lotto_farmaco_id'], ['lotti_farmaco.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_somministrazioni_animale_id'), 'somministrazioni', ['animale_id'], unique=False)
    op.create_index(op.f('ix_somministrazioni_data_ora'), 'somministrazioni', ['data_ora'], unique=False)
    op.create_index(op.f('ix_somministrazioni_deleted_at'), 'somministrazioni', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_somministrazioni_farmaco_id'), 'somministrazioni', ['farmaco_id'], unique=False)
    op.create_index(op.f('ix_somministrazioni_id'), 'somministrazioni', ['id'], unique=False)
    op.create_index(op.f('ix_somministrazioni_lotto_farmaco_id'), 'somministrazioni', ['lotto_farmaco_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_somministrazioni_lotto_farmaco_id'), table_name='somministrazioni')
    op.drop_index(op.f('ix_somministrazioni_id'), table_name='somministrazioni')
    op.drop_index(op.f('ix_somministrazioni_farmaco_id'), table_name='somministrazioni')
    op.drop_index(op.f('ix_somministrazioni_deleted_at'), table_name='somministrazioni')
    op.drop_index(op.f('ix_somministrazioni_data_ora'), table_name='somministrazioni')
    op.drop_index(op.f('ix_somministrazioni_animale_id'), table_name='somministrazioni')
    op.drop_table('somministrazioni')
    op.drop_index(op.f('ix_lotti_farmaco_scadenza'), table_name='lotti_farmaco')
    op.drop_index(op.f('ix_lotti_farmaco_id'), table_name='lotti_farmaco')
    op.drop_index(op.f('ix_lotti_farmaco_farmaco_id'), table_name='lotti_farmaco')
    op.drop_index(op.f('ix_lotti_farmaco_deleted_at'), table_name='lotti_farmaco')
    op.drop_index(op.f('ix_lotti_farmaco_azienda_id'), table_name='lotti_farmaco')
    op.drop_table('lotti_farmaco')
    op.drop_index(op.f('ix_farmaci_nome_commerciale'), table_name='farmaci')
    op.drop_index(op.f('ix_farmaci_id'), table_name='farmaci')
    op.drop_index(op.f('ix_farmaci_deleted_at'), table_name='farmaci')
    op.drop_table('farmaci')
    # ### end Alembic commands ###

