"""Initial migration - Allevamento tables

Revision ID: 1f7910bc273c
Revises: 
Create Date: 2025-10-29 13:55:27.086988

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f7910bc273c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('aziende',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('partita_iva', sa.String(length=11), nullable=True),
    sa.Column('codice_fiscale', sa.String(length=16), nullable=False),
    sa.Column('indirizzo', sa.Text(), nullable=True),
    sa.Column('telefono', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('tipo_allevamento', sa.String(length=20), nullable=True),
    sa.Column('ultima_sync_anagrafe', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("tipo_allevamento IN ('svezzamento', 'ingrasso', 'misto') OR tipo_allevamento IS NULL"),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codice_fiscale'),
    sa.UniqueConstraint('partita_iva')
    )
    op.create_index(op.f('ix_aziende_id'), 'aziende', ['id'], unique=False)
    op.create_table('sedi',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('azienda_id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('codice_stalla', sa.String(length=20), nullable=False),
    sa.Column('indirizzo', sa.Text(), nullable=True),
    sa.Column('latitudine', sa.Numeric(precision=10, scale=8), nullable=True),
    sa.Column('longitudine', sa.Numeric(precision=11, scale=8), nullable=True),
    sa.Column('tipo_allevamento', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("tipo_allevamento IN ('svezzamento', 'ingrasso', 'misto') OR tipo_allevamento IS NULL"),
    sa.ForeignKeyConstraint(['azienda_id'], ['aziende.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codice_stalla')
    )
    op.create_index(op.f('ix_sedi_id'), 'sedi', ['id'], unique=False)
    op.create_table('stabilimenti',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sede_id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('codice', sa.String(length=20), nullable=False),
    sa.Column('tipo', sa.String(length=50), nullable=True),
    sa.Column('capacita_totale', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['sede_id'], ['sedi.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sede_id', 'codice', name='uq_stabilimento_sede_codice')
    )
    op.create_index(op.f('ix_stabilimenti_id'), 'stabilimenti', ['id'], unique=False)
    op.create_table('box',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stabilimento_id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=50), nullable=False),
    sa.Column('codice', sa.String(length=20), nullable=False),
    sa.Column('capacita', sa.Integer(), nullable=False),
    sa.Column('tipo_allevamento', sa.String(length=20), nullable=True),
    sa.Column('stato', sa.String(length=20), server_default='libero', nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("stato IN ('libero', 'occupato', 'pulizia', 'manutenzione')"),
    sa.CheckConstraint("tipo_allevamento IN ('svezzamento', 'ingrasso', 'universale') OR tipo_allevamento IS NULL"),
    sa.ForeignKeyConstraint(['stabilimento_id'], ['stabilimenti.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stabilimento_id', 'codice', name='uq_box_stabilimento_codice')
    )
    op.create_index(op.f('ix_box_id'), 'box', ['id'], unique=False)
    op.create_table('animali',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('auricolare', sa.String(length=20), nullable=False),
    sa.Column('azienda_id', sa.Integer(), nullable=False),
    sa.Column('specie', sa.String(length=20), server_default='bovino', nullable=True),
    sa.Column('razza', sa.String(length=50), nullable=True),
    sa.Column('sesso', sa.String(length=1), nullable=True),
    sa.Column('data_nascita', sa.Date(), nullable=True),
    sa.Column('codice_elettronico', sa.String(length=50), nullable=True),
    sa.Column('codice_madre', sa.String(length=20), nullable=True),
    sa.Column('codice_assegnato_precedenza', sa.String(length=20), nullable=True),
    sa.Column('codice_azienda_anagrafe', sa.String(length=20), nullable=True),
    sa.Column('codice_provenienza', sa.String(length=20), nullable=True),
    sa.Column('identificativo_fiscale_provenienza', sa.String(length=20), nullable=True),
    sa.Column('specie_allevata_provenienza', sa.String(length=50), nullable=True),
    sa.Column('motivo_ingresso', sa.String(length=1), nullable=True),
    sa.Column('data_arrivo', sa.Date(), nullable=False),
    sa.Column('peso_arrivo', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('numero_modello_ingresso', sa.String(length=50), nullable=True),
    sa.Column('data_modello_ingresso', sa.Date(), nullable=True),
    sa.Column('tipo_allevamento', sa.String(length=20), nullable=True),
    sa.Column('peso_attuale', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('data_ultima_pesata', sa.Date(), nullable=True),
    sa.Column('stato', sa.String(length=20), server_default='presente', nullable=False),
    sa.Column('motivo_uscita', sa.String(length=1), nullable=True),
    sa.Column('data_uscita', sa.Date(), nullable=True),
    sa.Column('numero_modello_uscita', sa.String(length=50), nullable=True),
    sa.Column('data_modello_uscita', sa.Date(), nullable=True),
    sa.Column('codice_azienda_destinazione', sa.String(length=20), nullable=True),
    sa.Column('codice_fiera_destinazione', sa.String(length=20), nullable=True),
    sa.Column('codice_stato_destinazione', sa.String(length=20), nullable=True),
    sa.Column('regione_macello_destinazione', sa.String(length=100), nullable=True),
    sa.Column('codice_macello_destinazione', sa.String(length=20), nullable=True),
    sa.Column('codice_pascolo_destinazione', sa.String(length=20), nullable=True),
    sa.Column('codice_circo_destinazione', sa.String(length=20), nullable=True),
    sa.Column('data_macellazione', sa.Date(), nullable=True),
    sa.Column('abbattimento', sa.String(length=1), nullable=True),
    sa.Column('data_provvvedimento', sa.Date(), nullable=True),
    sa.Column('box_id', sa.Integer(), nullable=True),
    sa.Column('data_inserimento_box', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('origine_dati', sa.String(length=20), server_default='manuale', nullable=False),
    sa.Column('ultima_sync_anagrafe', sa.DateTime(timezone=True), nullable=True),
    sa.Column('data_estrazione_dati_anagrafe', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("origine_dati IN ('manuale', 'anagrafe', 'misto')"),
    sa.CheckConstraint("sesso IN ('M', 'F') OR sesso IS NULL"),
    sa.CheckConstraint("stato IN ('presente', 'venduto', 'deceduto', 'trasferito', 'macellato')"),
    sa.CheckConstraint("tipo_allevamento IN ('svezzamento', 'ingrasso', 'universale') OR tipo_allevamento IS NULL"),
    sa.ForeignKeyConstraint(['azienda_id'], ['aziende.id'], ),
    sa.ForeignKeyConstraint(['box_id'], ['box.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('auricolare')
    )
    op.create_index(op.f('ix_animali_id'), 'animali', ['id'], unique=False)
    op.create_table('decessi',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('animale_id', sa.Integer(), nullable=False),
    sa.Column('data_ora', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('causa', sa.String(length=100), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('valore_capo', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('costi_fino_al_decesso', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('perdita_totale', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('tipo_contratto', sa.String(length=50), nullable=True),
    sa.Column('quota_decesso', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('responsabile', sa.String(length=20), nullable=True),
    sa.Column('giorni_dall_arrivo', sa.Integer(), nullable=True),
    sa.Column('entro_termine_responsabilita', sa.Boolean(), nullable=True),
    sa.Column('limite_esonero', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('fattura_smaltimento_id', sa.Integer(), nullable=True),
    sa.Column('costo_smaltimento', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['animale_id'], ['animali.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('animale_id')
    )
    op.create_index(op.f('ix_decessi_id'), 'decessi', ['id'], unique=False)
    op.create_table('movimentazioni',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('animale_id', sa.Integer(), nullable=False),
    sa.Column('da_box_id', sa.Integer(), nullable=True),
    sa.Column('a_box_id', sa.Integer(), nullable=False),
    sa.Column('data_ora', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('operatore_id', sa.Integer(), nullable=True),
    sa.Column('motivo', sa.String(length=100), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['a_box_id'], ['box.id'], ),
    sa.ForeignKeyConstraint(['animale_id'], ['animali.id'], ),
    sa.ForeignKeyConstraint(['da_box_id'], ['box.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_movimentazioni_id'), 'movimentazioni', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_movimentazioni_id'), table_name='movimentazioni')
    op.drop_table('movimentazioni')
    op.drop_index(op.f('ix_decessi_id'), table_name='decessi')
    op.drop_table('decessi')
    op.drop_index(op.f('ix_animali_id'), table_name='animali')
    op.drop_table('animali')
    op.drop_index(op.f('ix_box_id'), table_name='box')
    op.drop_table('box')
    op.drop_index(op.f('ix_stabilimenti_id'), table_name='stabilimenti')
    op.drop_table('stabilimenti')
    op.drop_index(op.f('ix_sedi_id'), table_name='sedi')
    op.drop_table('sedi')
    op.drop_index(op.f('ix_aziende_id'), table_name='aziende')
    op.drop_table('aziende')
    # ### end Alembic commands ###

