"""add_note_to_componente_alimentare

Revision ID: 5638ef08af37
Revises: 563b79b3c1bc
Create Date: 2025-10-30 11:24:25.849997

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5638ef08af37'
down_revision = '563b79b3c1bc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('componenti_alimentari', sa.Column('note', sa.Text(), nullable=True))
    op.create_index(op.f('ix_componenti_alimentari_deleted_at'), 'componenti_alimentari', ['deleted_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_componenti_alimentari_deleted_at'), table_name='componenti_alimentari')
    op.drop_column('componenti_alimentari', 'note')
    # ### end Alembic commands ###

