"""alimentazione_module_tables

Revision ID: 563b79b3c1bc
Revises: 01ce1ccd56e3
Create Date: 2025-10-30 11:15:56.433584

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '563b79b3c1bc'
down_revision = '01ce1ccd56e3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('componenti_alimentari',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('tipo', sa.String(length=50), nullable=True),
    sa.Column('unita_misura', sa.String(length=20), nullable=True),
    sa.Column('autoprodotto', sa.Boolean(), nullable=True),
    sa.Column('costo_unitario', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('per_svezzamento', sa.Boolean(), nullable=True),
    sa.Column('per_ingrasso', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_index(op.f('ix_componenti_alimentari_id'), 'componenti_alimentari', ['id'], unique=False)
    op.create_table('fornitori',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('partita_iva', sa.String(length=20), nullable=True),
    sa.Column('indirizzo', sa.String(length=250), nullable=True),
    sa.Column('telefono', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=150), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('partita_iva')
    )
    op.create_index(op.f('ix_fornitori_deleted_at'), 'fornitori', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_fornitori_id'), 'fornitori', ['id'], unique=False)
    op.create_table('piani_alimentazione',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('descrizione', sa.Text(), nullable=True),
    sa.Column('tipo_allevamento', sa.String(length=20), nullable=True),
    sa.Column('versione', sa.String(length=20), nullable=True),
    sa.Column('validita_da', sa.Date(), nullable=True),
    sa.Column('validita_a', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_piani_alimentazione_deleted_at'), 'piani_alimentazione', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_piani_alimentazione_id'), 'piani_alimentazione', ['id'], unique=False)
    op.create_table('fatture',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data', sa.Date(), nullable=True),
    sa.Column('numero', sa.String(length=50), nullable=False),
    sa.Column('fornitore_id', sa.Integer(), nullable=True),
    sa.Column('importo', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['fornitore_id'], ['fornitori.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fatture_deleted_at'), 'fatture', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_fatture_fornitore_id'), 'fatture', ['fornitore_id'], unique=False)
    op.create_index(op.f('ix_fatture_id'), 'fatture', ['id'], unique=False)
    op.create_table('mangimi_confezionati',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('fornitore_id', sa.Integer(), nullable=True),
    sa.Column('tipo_allevamento', sa.String(length=20), nullable=True),
    sa.Column('prezzo_unitario', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('unita_misura', sa.String(length=20), nullable=True),
    sa.Column('fattura_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['fattura_id'], ['fatture.id'], ),
    sa.ForeignKeyConstraint(['fornitore_id'], ['fornitori.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mangimi_confezionati_id'), 'mangimi_confezionati', ['id'], unique=False)
    op.create_table('composizione_piano',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('piano_alimentazione_id', sa.Integer(), nullable=True),
    sa.Column('componente_alimentare_id', sa.Integer(), nullable=True),
    sa.Column('mangime_confezionato_id', sa.Integer(), nullable=True),
    sa.Column('quantita', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.Column('ordine', sa.Integer(), nullable=True),
    sa.Column('tipo_fornitura', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['componente_alimentare_id'], ['componenti_alimentari.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['mangime_confezionato_id'], ['mangimi_confezionati.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['piano_alimentazione_id'], ['piani_alimentazione.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_composizione_piano_deleted_at'), 'composizione_piano', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_composizione_piano_id'), 'composizione_piano', ['id'], unique=False)
    op.create_table('registro_alimentazione',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('box_id', sa.Integer(), nullable=True),
    sa.Column('data', sa.Date(), nullable=True),
    sa.Column('razione_id', sa.Integer(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['box_id'], ['box.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['razione_id'], ['piani_alimentazione.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_registro_alimentazione_deleted_at'), 'registro_alimentazione', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_registro_alimentazione_id'), 'registro_alimentazione', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_registro_alimentazione_id'), table_name='registro_alimentazione')
    op.drop_index(op.f('ix_registro_alimentazione_deleted_at'), table_name='registro_alimentazione')
    op.drop_table('registro_alimentazione')
    op.drop_index(op.f('ix_composizione_piano_id'), table_name='composizione_piano')
    op.drop_index(op.f('ix_composizione_piano_deleted_at'), table_name='composizione_piano')
    op.drop_table('composizione_piano')
    op.drop_index(op.f('ix_mangimi_confezionati_id'), table_name='mangimi_confezionati')
    op.drop_table('mangimi_confezionati')
    op.drop_index(op.f('ix_fatture_id'), table_name='fatture')
    op.drop_index(op.f('ix_fatture_fornitore_id'), table_name='fatture')
    op.drop_index(op.f('ix_fatture_deleted_at'), table_name='fatture')
    op.drop_table('fatture')
    op.drop_index(op.f('ix_piani_alimentazione_id'), table_name='piani_alimentazione')
    op.drop_index(op.f('ix_piani_alimentazione_deleted_at'), table_name='piani_alimentazione')
    op.drop_table('piani_alimentazione')
    op.drop_index(op.f('ix_fornitori_id'), table_name='fornitori')
    op.drop_index(op.f('ix_fornitori_deleted_at'), table_name='fornitori')
    op.drop_table('fornitori')
    op.drop_index(op.f('ix_componenti_alimentari_id'), table_name='componenti_alimentari')
    op.drop_table('componenti_alimentari')
    # ### end Alembic commands ###

