"""Remove tipo_allevamento from aziende and sedi

Revision ID: 89df08758288
Revises: 1f7910bc273c
Create Date: 2025-10-29 14:33:03.834991

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89df08758288'
down_revision = '1f7910bc273c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('aziende', 'tipo_allevamento')
    op.drop_column('sedi', 'tipo_allevamento')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sedi', sa.Column('tipo_allevamento', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.add_column('aziende', sa.Column('tipo_allevamento', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    # ### end Alembic commands ###

