"""amministrazione_module_tables

Revision ID: d123456789ab
Revises: c0ffee123456
Create Date: 2025-01-28 12:00:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd123456789ab'
down_revision = 'c0ffee123456'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Tabella Fornitori Tipi
    op.create_table('fornitori_tipi',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('fornitore_id', sa.Integer(), nullable=False),
        sa.Column('categoria', sa.String(length=50), nullable=False),
        sa.Column('note', sa.String(length=500), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(['fornitore_id'], ['fornitori.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fornitori_tipi_id'), 'fornitori_tipi', ['id'], unique=False)
    op.create_index(op.f('ix_fornitori_tipi_fornitore_id'), 'fornitori_tipi', ['fornitore_id'], unique=False)
    op.create_index(op.f('ix_fornitori_tipi_categoria'), 'fornitori_tipi', ['categoria'], unique=False)
    
    # Tabella Vendite Prodotti Agricoli
    op.create_table('vendite_prodotti_agricoli',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('azienda_id', sa.Integer(), nullable=False),
        sa.Column('prodotto', sa.String(length=200), nullable=False),
        sa.Column('data_vendita', sa.Date(), nullable=False),
        sa.Column('quantita', sa.Numeric(precision=12, scale=3), nullable=False),
        sa.Column('unita_misura', sa.String(length=20), nullable=True, server_default='kg'),
        sa.Column('prezzo_unitario', sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column('importo_totale', sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column('terreno_id', sa.Integer(), nullable=True),
        sa.Column('raccolto_id', sa.Integer(), nullable=True),
        sa.Column('acquirente', sa.String(length=200), nullable=True),
        sa.Column('numero_fattura', sa.String(length=50), nullable=True),
        sa.Column('numero_ddt', sa.String(length=50), nullable=True),
        sa.Column('costi_terreno_totale', sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column('costi_terreno_quantita', sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column('margine', sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column('note', sa.Text(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(['azienda_id'], ['aziende.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['terreno_id'], ['terreni.id'], ondelete='SET NULL'),
        sa.ForeignKeyConstraint(['raccolto_id'], ['raccolti_terreno.id'], ondelete='SET NULL'),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vendite_prodotti_agricoli_id'), 'vendite_prodotti_agricoli', ['id'], unique=False)
    op.create_index(op.f('ix_vendite_prodotti_agricoli_azienda_id'), 'vendite_prodotti_agricoli', ['azienda_id'], unique=False)
    op.create_index(op.f('ix_vendite_prodotti_agricoli_prodotto'), 'vendite_prodotti_agricoli', ['prodotto'], unique=False)
    op.create_index(op.f('ix_vendite_prodotti_agricoli_data_vendita'), 'vendite_prodotti_agricoli', ['data_vendita'], unique=False)
    op.create_index(op.f('ix_vendite_prodotti_agricoli_terreno_id'), 'vendite_prodotti_agricoli', ['terreno_id'], unique=False)
    op.create_index(op.f('ix_vendite_prodotti_agricoli_raccolto_id'), 'vendite_prodotti_agricoli', ['raccolto_id'], unique=False)
    op.create_index(op.f('ix_vendite_prodotti_agricoli_deleted_at'), 'vendite_prodotti_agricoli', ['deleted_at'], unique=False)
    
    # Tabella Prodotti Derivati
    op.create_table('prodotti_derivati',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('raccolto_id', sa.Integer(), nullable=False),
        sa.Column('nome_prodotto', sa.String(length=200), nullable=False),
        sa.Column('quantita_prodotta', sa.Numeric(precision=12, scale=3), nullable=False),
        sa.Column('unita_misura', sa.String(length=20), nullable=True, server_default='kg'),
        sa.Column('destinazione', sa.String(length=50), nullable=False),
        sa.Column('componente_alimentare_id', sa.Integer(), nullable=True),
        sa.Column('prezzo_vendita', sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column('importo_vendita', sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column('valore_equivalente', sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column('note', sa.Text(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(['raccolto_id'], ['raccolti_terreno.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['componente_alimentare_id'], ['componenti_alimentari.id'], ondelete='SET NULL'),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prodotti_derivati_id'), 'prodotti_derivati', ['id'], unique=False)
    op.create_index(op.f('ix_prodotti_derivati_raccolto_id'), 'prodotti_derivati', ['raccolto_id'], unique=False)
    op.create_index(op.f('ix_prodotti_derivati_destinazione'), 'prodotti_derivati', ['destinazione'], unique=False)
    op.create_index(op.f('ix_prodotti_derivati_componente_alimentare_id'), 'prodotti_derivati', ['componente_alimentare_id'], unique=False)
    op.create_index(op.f('ix_prodotti_derivati_deleted_at'), 'prodotti_derivati', ['deleted_at'], unique=False)
    
    # Tabella Fatture Amministrazione
    # Crea gli ENUM per PostgreSQL
    connection = op.get_bind()
    if connection.dialect.name == 'postgresql':
        tipo_fattura_enum = postgresql.ENUM('entrata', 'uscita', name='tipofattura', create_type=False)
        tipo_fattura_enum.create(connection, checkfirst=True)
        
        stato_pagamento_enum = postgresql.ENUM('da_pagare', 'pagata', 'scaduta', 'parziale', name='statopagamento', create_type=False)
        stato_pagamento_enum.create(connection, checkfirst=True)
    else:
        # Per database non-PostgreSQL, usa String
        tipo_fattura_enum = sa.String(length=20)
        stato_pagamento_enum = sa.String(length=20)
    
    op.create_table('fatture_amministrazione',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('fattura_id', sa.Integer(), nullable=True),
        sa.Column('tipo', tipo_fattura_enum, nullable=False, server_default='entrata'),
        sa.Column('numero', sa.String(length=50), nullable=False),
        sa.Column('data_fattura', sa.Date(), nullable=False),
        sa.Column('data_registrazione', sa.Date(), nullable=False, server_default=sa.text('CURRENT_DATE')),
        sa.Column('fornitore_id', sa.Integer(), nullable=True),
        sa.Column('importo_totale', sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column('importo_iva', sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column('importo_netto', sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column('importo_pagato', sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column('stato_pagamento', stato_pagamento_enum, nullable=False, server_default='da_pagare'),
        sa.Column('data_scadenza', sa.Date(), nullable=True),
        sa.Column('data_pagamento', sa.Date(), nullable=True),
        sa.Column('periodo_da', sa.Date(), nullable=True),
        sa.Column('periodo_a', sa.Date(), nullable=True),
        sa.Column('periodo_attribuzione', sa.String(length=100), nullable=True),
        sa.Column('categoria', sa.String(length=100), nullable=True),
        sa.Column('note', sa.Text(), nullable=True),
        sa.Column('allegato_path', sa.String(length=500), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(['fattura_id'], ['fatture.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['fornitore_id'], ['fornitori.id'], ondelete='SET NULL'),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fatture_amministrazione_id'), 'fatture_amministrazione', ['id'], unique=False)
    op.create_index(op.f('ix_fatture_amministrazione_fattura_id'), 'fatture_amministrazione', ['fattura_id'], unique=False)
    op.create_index(op.f('ix_fatture_amministrazione_fornitore_id'), 'fatture_amministrazione', ['fornitore_id'], unique=False)
    op.create_index(op.f('ix_fatture_amministrazione_numero'), 'fatture_amministrazione', ['numero'], unique=False)
    op.create_index(op.f('ix_fatture_amministrazione_data_fattura'), 'fatture_amministrazione', ['data_fattura'], unique=False)
    op.create_index(op.f('ix_fatture_amministrazione_data_scadenza'), 'fatture_amministrazione', ['data_scadenza'], unique=False)
    op.create_index(op.f('ix_fatture_amministrazione_categoria'), 'fatture_amministrazione', ['categoria'], unique=False)
    op.create_index(op.f('ix_fatture_amministrazione_deleted_at'), 'fatture_amministrazione', ['deleted_at'], unique=False)
    
    # Tabella Partite Animali
    connection = op.get_bind()
    if connection.dialect.name == 'postgresql':
        tipo_partita_enum = postgresql.ENUM('ingresso', 'uscita', name='tipopartita', create_type=False)
        tipo_partita_enum.create(connection, checkfirst=True)
    else:
        tipo_partita_enum = sa.String(length=20)
    
    op.create_table('partite_animali',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('azienda_id', sa.Integer(), nullable=False),
        sa.Column('tipo', tipo_partita_enum, nullable=False),
        sa.Column('data', sa.Date(), nullable=False),
        sa.Column('numero_partita', sa.String(length=50), nullable=True),
        sa.Column('codice_stalla', sa.String(length=20), nullable=False),
        sa.Column('nome_stalla', sa.String(length=200), nullable=True),
        sa.Column('numero_capi', sa.Integer(), nullable=False),
        sa.Column('peso_totale', sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column('peso_medio', sa.Numeric(precision=6, scale=2), nullable=True),
        sa.Column('pesi_individuali', sa.Text(), nullable=True),
        sa.Column('file_anagrafe_origine', sa.String(length=500), nullable=True),
        sa.Column('data_importazione', sa.DateTime(timezone=True), nullable=True),
        sa.Column('motivo', sa.String(length=1), nullable=True),
        sa.Column('numero_modello', sa.String(length=50), nullable=True),
        sa.Column('note', sa.Text(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(['azienda_id'], ['aziende.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('numero_partita')
    )
    op.create_index(op.f('ix_partite_animali_id'), 'partite_animali', ['id'], unique=False)
    op.create_index(op.f('ix_partite_animali_azienda_id'), 'partite_animali', ['azienda_id'], unique=False)
    op.create_index(op.f('ix_partite_animali_tipo'), 'partite_animali', ['tipo'], unique=False)
    op.create_index(op.f('ix_partite_animali_data'), 'partite_animali', ['data'], unique=False)
    op.create_index(op.f('ix_partite_animali_codice_stalla'), 'partite_animali', ['codice_stalla'], unique=False)
    op.create_index(op.f('ix_partite_animali_deleted_at'), 'partite_animali', ['deleted_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_partite_animali_deleted_at'), table_name='partite_animali')
    op.drop_index(op.f('ix_partite_animali_codice_stalla'), table_name='partite_animali')
    op.drop_index(op.f('ix_partite_animali_data'), table_name='partite_animali')
    op.drop_index(op.f('ix_partite_animali_tipo'), table_name='partite_animali')
    op.drop_index(op.f('ix_partite_animali_azienda_id'), table_name='partite_animali')
    op.drop_index(op.f('ix_partite_animali_id'), table_name='partite_animali')
    op.drop_table('partite_animali')
    
    op.drop_index(op.f('ix_fatture_amministrazione_deleted_at'), table_name='fatture_amministrazione')
    op.drop_index(op.f('ix_fatture_amministrazione_categoria'), table_name='fatture_amministrazione')
    op.drop_index(op.f('ix_fatture_amministrazione_data_scadenza'), table_name='fatture_amministrazione')
    op.drop_index(op.f('ix_fatture_amministrazione_data_fattura'), table_name='fatture_amministrazione')
    op.drop_index(op.f('ix_fatture_amministrazione_numero'), table_name='fatture_amministrazione')
    op.drop_index(op.f('ix_fatture_amministrazione_fornitore_id'), table_name='fatture_amministrazione')
    op.drop_index(op.f('ix_fatture_amministrazione_fattura_id'), table_name='fatture_amministrazione')
    op.drop_index(op.f('ix_fatture_amministrazione_id'), table_name='fatture_amministrazione')
    op.drop_table('fatture_amministrazione')
    
    op.drop_index(op.f('ix_prodotti_derivati_deleted_at'), table_name='prodotti_derivati')
    op.drop_index(op.f('ix_prodotti_derivati_componente_alimentare_id'), table_name='prodotti_derivati')
    op.drop_index(op.f('ix_prodotti_derivati_destinazione'), table_name='prodotti_derivati')
    op.drop_index(op.f('ix_prodotti_derivati_raccolto_id'), table_name='prodotti_derivati')
    op.drop_index(op.f('ix_prodotti_derivati_id'), table_name='prodotti_derivati')
    op.drop_table('prodotti_derivati')
    
    op.drop_index(op.f('ix_vendite_prodotti_agricoli_deleted_at'), table_name='vendite_prodotti_agricoli')
    op.drop_index(op.f('ix_vendite_prodotti_agricoli_raccolto_id'), table_name='vendite_prodotti_agricoli')
    op.drop_index(op.f('ix_vendite_prodotti_agricoli_terreno_id'), table_name='vendite_prodotti_agricoli')
    op.drop_index(op.f('ix_vendite_prodotti_agricoli_data_vendita'), table_name='vendite_prodotti_agricoli')
    op.drop_index(op.f('ix_vendite_prodotti_agricoli_prodotto'), table_name='vendite_prodotti_agricoli')
    op.drop_index(op.f('ix_vendite_prodotti_agricoli_azienda_id'), table_name='vendite_prodotti_agricoli')
    op.drop_index(op.f('ix_vendite_prodotti_agricoli_id'), table_name='vendite_prodotti_agricoli')
    op.drop_table('vendite_prodotti_agricoli')
    
    op.drop_index(op.f('ix_fornitori_tipi_categoria'), table_name='fornitori_tipi')
    op.drop_index(op.f('ix_fornitori_tipi_fornitore_id'), table_name='fornitori_tipi')
    op.drop_index(op.f('ix_fornitori_tipi_id'), table_name='fornitori_tipi')
    op.drop_table('fornitori_tipi')
    
    # Drop ENUMs (solo per PostgreSQL)
    connection = op.get_bind()
    if connection.dialect.name == 'postgresql':
        tipo_fattura_enum = postgresql.ENUM('entrata', 'uscita', name='tipofattura', create_type=False)
        tipo_fattura_enum.drop(connection, checkfirst=True)
        
        stato_pagamento_enum = postgresql.ENUM('da_pagare', 'pagata', 'scaduta', 'parziale', name='statopagamento', create_type=False)
        stato_pagamento_enum.drop(connection, checkfirst=True)
        
        tipo_partita_enum = postgresql.ENUM('ingresso', 'uscita', name='tipopartita', create_type=False)
        tipo_partita_enum.drop(connection, checkfirst=True)
    # ### end Alembic commands ###

